train:
  batch_size: 4
  seed: 42
  image_size: [640, 360]
  num_classes: 2 # person, objecT(dog, cat)
  learning_rate: 0.001 #0.005 0.001 0.007
  scheduler: 'ReduceLROnPlateau' # StepLR
  optimizer: 'SGD' # SGD
  epochs: 30
  model_name: 'retinanet'
  iou_threshold: 0.5
  confidence_threshold: 0.5
  device: 4
  early_stop: True 
  early_stop_patience: 8

log:
  project: 'Pedestrian-Detection-all-re'
  entity: 'finallyupper'

test:
  input_video_path: '/home/yoojinoh/Others/PR/data/videos/test_video1.mp4'
  num_classes: 2
  score_threshold: 0.25 # 0.25 0.4
  iou_threshold: 0.3
  confidence_threshold: 0.3
  device: 5
  warning_distance: 167

