pedestrian: 
  model_path: /home/yoojinoh/Others/PR/data/weights/pedestrian.pth
  iou_threshold: 0.3
  confidence_threshold: 0.3
  warning_distance: 180
  num_classes: 2

traffic_light:
  model_path: /home/yoojinoh/Others/PR/data/weights/traffic_light.pth
  num_classes: 13
  
lane: 
  model_path: /home/yoojinoh/Others/PR/data/weights/lane.pth
  model_type: ENet
  lane_merge_thr: 5 # Recommended to set btw 3 ~ 10

device: 5
